/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.26.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { anyApi } from "convex/server";

const api = anyApi;

export default api;
export { api };