/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.26.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const api: FilterApi<
  ApiFromModules<{
    "tasks": {
      create: FunctionReference<"mutation", "public", { title: string; description?: string; userId: string }, any>,
      list: FunctionReference<"query", "public", { userId: string }, any>,
      update: FunctionReference<"mutation", "public", { id: any; title?: string; description?: string; completed?: boolean }, any>,
      remove: FunctionReference<"mutation", "public", { id: any }, any>
    }
  }>,
  FunctionReference<any, "public">
>;
export default api;