/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.26.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

const api = {
  tasks: {
    create: { _type: 'mutation' },
    list: { _type: 'query' },
    update: { _type: 'mutation' },
    remove: { _type: 'mutation' }
  }
};

export default api;
export { api };