/* eslint-disable */
/**
 * Generated server utilities.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.26.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

// Simple implementation for build-time compatibility
export const mutation = (func) => {
  return {
    _type: 'mutation',
    _args: func.args,
    _handler: func.handler
  };
};

export const query = (func) => {
  return {
    _type: 'query',
    _args: func.args,
    _handler: func.handler
  };
};

export const action = (func) => {
  return {
    _type: 'action',
    _args: func.args,
    _handler: func.handler
  };
};